# Generated by Django 3.2.10 on 2023-06-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='name',
            new_name='buyer_name',
        ),
    ]
