# Generated by Django 3.2.10 on 2023-05-27 05:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='exp_date_of_delivery',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
