# Generated by Django 3.2.10 on 2023-05-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_no',
            new_name='file',
        ),
    ]
