# Generated by Django 4.2.6 on 2023-11-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='color',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
