# Generated by Django 3.2.10 on 2023-09-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size_range',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='sleve',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
