# Generated by Django 3.2.10 on 2023-08-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
