# Generated by Django 4.1.6 on 2023-04-10 08:59

from django.db import migrations, models
import purchase_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='po_no',
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='po_id',
            field=models.IntegerField(default=purchase_order.models.generate_random_number),
        ),
    ]
