# Generated by Django 4.2.6 on 2023-11-05 11:36

from django.db import migrations, models
import purchase_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='work_order',
            field=models.CharField(default=purchase_order.models.generate_random_number, max_length=64, unique=True),
        ),
    ]
