# Generated by Django 3.2.10 on 2023-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='order_qty',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
