# Generated by Django 3.2.10 on 2023-06-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='sale_contact',
            new_name='master_lc_sc',
        ),
    ]
