# Generated by Django 3.2.10 on 2023-07-31 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='wo_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
