# Generated by Django 4.1.7 on 2023-05-07 05:10

from django.db import migrations, models
import purchase_order.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='po_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='work_order',
            field=models.IntegerField(default=purchase_order.models.generate_random_number),
        ),
    ]
