# Generated by Django 3.1.13 on 2023-01-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='po_no',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
