# Generated by Django 4.1.6 on 2023-04-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_remove_purchasebill_po_no_purchasebill_po_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='current_date',
            field=models.DateField(auto_now_add=True, default='2023-04-11'),
            preserve_default=False,
        ),
    ]
