# Generated by Django 4.1.7 on 2023-05-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0002_alter_purchasebill_po_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='detail',
            new_name='remarks',
        ),
    ]
