# Generated by Django 4.1.6 on 2023-04-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_purchasebill_current_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='current_date',
        ),
    ]
