# Generated by Django 4.2.6 on 2023-11-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchasebill_work_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='style_no',
            new_name='styleORorder_no',
        ),
    ]
