# Generated by Django 3.2.10 on 2023-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_alter_purchaseitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
