# Generated by Django 3.2.10 on 2023-05-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_rename_file_no_file_file'),
        ('purchase_order', '0003_alter_purchasebill_file_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='file_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
