# Generated by Django 4.1.7 on 2023-05-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0003_rename_detail_purchasebill_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
