# Generated by Django 4.2.6 on 2023-11-19 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_rename_style_no_purchasebill_styleororder_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='styleORorder_no',
            new_name='style_no',
        ),
    ]
