# Generated by Django 3.2.10 on 2023-08-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_auto_20230807_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='totalprice',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_price',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
