# Generated by Django 4.1.7 on 2023-05-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_alter_purchasebill_file_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasebill',
            old_name='po_id',
            new_name='po_no',
        ),
        migrations.RenameField(
            model_name='purchasebill',
            old_name='po_date',
            new_name='wo_date',
        ),
    ]
