# Generated by Django 3.2.10 on 2023-08-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0005_auto_20230814_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
