# Generated by Django 3.2.10 on 2023-08-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_purchaseitem_stock_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock_qty',
        ),
    ]
