# Generated by Django 4.1.7 on 2023-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0006_rename_po_id_purchasebill_po_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='sale_contact',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='style',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
