# Generated by Django 3.2.10 on 2023-08-06 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('unit', '0001_initial'),
        ('purchase_order', '0001_initial'),
        ('remarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreBill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(max_length=64, null=True)),
                ('buyer_name', models.CharField(max_length=64, null=True)),
                ('report', models.CharField(choices=[('', 'Select'), ('Invoice', 'Invoice'), ('DC', 'DC')], max_length=64, null=True)),
                ('report_no', models.CharField(blank=True, max_length=64, null=True)),
                ('report_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('pi_no', models.CharField(blank=True, max_length=150, null=True)),
                ('received_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('img_file', models.ImageField(blank=True, default='blank.png', null=True, upload_to='store')),
                ('master_lc_sc', models.CharField(max_length=64, null=True)),
                ('style_no', models.CharField(blank=True, max_length=32, null=True)),
                ('fileno_po', models.CharField(max_length=64, null=True)),
                ('lot_no', models.CharField(blank=True, max_length=64, null=True)),
                ('store_location', models.CharField(blank=True, max_length=64, null=True)),
                ('order_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarksname_store', to='remarks.remarks')),
                ('work_order_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_file_no', to='purchase_order.purchasebill')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('fabric_color', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storebillno', to='store.storebill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeitem', to='stock.stock')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_store', to='unit.unit')),
            ],
        ),
        migrations.CreateModel(
            name='StoreBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storedetailsbillno', to='store.storebill')),
            ],
        ),
    ]
