# Generated by Django 3.2.10 on 2023-08-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='remarks',
            new_name='remarks_store',
        ),
    ]
