# Generated by Django 3.2.10 on 2023-06-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='lc',
            new_name='master_lc_sc',
        ),
    ]
