# Generated by Django 4.1.7 on 2023-05-09 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='storebill',
            name='received_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
