# Generated by Django 3.2.10 on 2023-06-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='supplier',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
