# Generated by Django 4.1.7 on 2023-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='store'),
        ),
    ]
