# Generated by Django 3.2.10 on 2023-07-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='work_order',
            new_name='fileno_po',
        ),
        migrations.RenameField(
            model_name='storebill',
            old_name='file_no_store',
            new_name='work_order_store',
        ),
    ]
