# Generated by Django 3.1.13 on 2022-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='due_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
