# Generated by Django 4.2.6 on 2023-10-15 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='fabric_color',
            new_name='color',
        ),
    ]
