# Generated by Django 4.1.7 on 2023-05-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='po_no',
            new_name='wo_no',
        ),
    ]
