# Generated by Django 4.1.7 on 2023-04-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='unit_price',
        ),
    ]
