# Generated by Django 3.2.10 on 2023-07-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storebill_received_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebill',
            name='received_by',
        ),
    ]
