# Generated by Django 3.2.10 on 2023-05-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0004_alter_purchasebill_file_no'),
        ('store', '0002_alter_storebill_file_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='file_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_order.purchasebill'),
        ),
    ]
