# Generated by Django 4.1.7 on 2023-05-07 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_po_no_storebill_wo_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='wo_no',
            new_name='po_no',
        ),
        migrations.RenameField(
            model_name='storebill',
            old_name='fabric_detail',
            new_name='remarks',
        ),
    ]
