# Generated by Django 3.2.10 on 2023-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230806_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebill',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
