# Generated by Django 3.2.10 on 2023-08-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_remarks_storebill_remarks_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='remarks_store',
            new_name='remarks',
        ),
    ]
