# Generated by Django 3.2.10 on 2023-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storebill_stock_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebill',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='storeitem',
            name='stock_qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
