# Generated by Django 4.2.6 on 2023-11-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_work_order_store_storebill_work_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='today_received_quantity',
            new_name='received_quantity',
        ),
    ]
