# Generated by Django 4.1.7 on 2023-05-07 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_wo_no_storebill_po_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='po_no',
            new_name='wo_no',
        ),
    ]
