# Generated by Django 3.2.10 on 2023-05-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_storebill_file_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebill',
            old_name='file_no',
            new_name='file_no_wo',
        ),
    ]
