# Generated by Django 3.2.10 on 2023-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230814_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='stock_qty',
        ),
    ]
