# Generated by Django 3.2.10 on 2023-07-31 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_storebill_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='report_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
