# Generated by Django 4.2.6 on 2023-11-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_today_received_quantity_storeitem_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
