# Generated by Django 4.1.7 on 2023-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_po_no_storebill_wo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
