# Generated by Django 4.2.6 on 2023-11-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_storeitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebill',
            name='po_no',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
