# Generated by Django 3.2.10 on 2023-09-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_storebill_received_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='today_received_qty',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='wo_quantity',
        ),
    ]
