# Generated by Django 3.2.10 on 2023-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_storeitem_stock_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='balance_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
