# Generated by Django 3.2.10 on 2023-08-01 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_storebill_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebill',
            name='report_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
