# Generated by Django 3.2.10 on 2023-09-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230912_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='today_received_quantity',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeitem',
            name='wo_quantity',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
            preserve_default=False,
        ),
    ]
