# Generated by Django 3.1.13 on 2022-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_receiver', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('buyer_name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('po_no', models.CharField(blank=True, max_length=32, null=True)),
                ('order_no', models.CharField(blank=True, max_length=32, null=True)),
                ('style_no', models.CharField(blank=True, max_length=32, null=True)),
                ('card_no', models.CharField(blank=True, max_length=32, null=True)),
                ('colour', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('floor', models.CharField(choices=[('', 'Select'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=64, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('order_qty', models.PositiveIntegerField(default=1)),
                ('uom', models.CharField(choices=[('', 'Select'), ('kg', 'kg'), ('miter', 'miter'), ('yard', 'yard'), ('pcs', 'pcs'), ('pound', 'pound'), ('g', 'g'), ('gg', 'gg'), ('litre', 'litre'), ('dg', 'dg'), ('1000 pcs', '1000 pcs')], max_length=64, null=True)),
                ('cutting_qty', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('consumption', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('req_qty', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('supply_qty', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('srf_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_receiver.storereceiver')),
            ],
        ),
    ]
