# Generated by Django 4.1.3 on 2022-12-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisition',
            name='floor',
            field=models.CharField(choices=[('', 'Select'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], max_length=64, null=True),
        ),
    ]
