# Generated by Django 3.2.10 on 2023-08-20 04:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        ('remarks', '0001_initial'),
        ('stock', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesRequisitionBill',
            fields=[
                ('billno', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('order_no', models.CharField(blank=True, max_length=32, null=True)),
                ('style_no', models.CharField(blank=True, max_length=32, null=True)),
                ('fileno_po', models.CharField(max_length=64, null=True)),
                ('line_no', models.CharField(blank=True, max_length=32, null=True)),
                ('card_no', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('supply_qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acces_wo_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_wo_no', to='store.storebill')),
                ('remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarksname_acces', to='remarks.remarks')),
            ],
        ),
        migrations.CreateModel(
            name='AccesRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, default=1, null=True)),
                ('balance_quantity', models.FloatField(default=0)),
                ('acces_color', models.CharField(blank=True, max_length=64, null=True)),
                ('size', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('style', models.CharField(blank=True, max_length=64, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_billno', to='acces_requisition.accesrequisitionbill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_item', to='stock.stock')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_of_a_issue', to='unit.unit')),
            ],
        ),
        migrations.CreateModel(
            name='AccesRequisitionBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eway', models.CharField(blank=True, max_length=50, null=True)),
                ('veh', models.CharField(blank=True, max_length=50, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('po', models.CharField(blank=True, max_length=50, null=True)),
                ('cgst', models.CharField(blank=True, max_length=50, null=True)),
                ('sgst', models.CharField(blank=True, max_length=50, null=True)),
                ('igst', models.CharField(blank=True, max_length=50, null=True)),
                ('cess', models.CharField(blank=True, max_length=50, null=True)),
                ('tcs', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_detailsbillno', to='acces_requisition.accesrequisitionbill')),
            ],
        ),
    ]
