# Generated by Django 4.1.7 on 2023-05-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesrequisitionbill',
            name='file_no',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
