# Generated by Django 3.2.10 on 2023-09-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesrequisitionbill',
            name='po_no',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
