# Generated by Django 4.1.6 on 2023-04-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesrequisitionitem',
            name='totalprice',
        ),
        migrations.RemoveField(
            model_name='accesrequisitionitem',
            name='unit_price',
        ),
    ]
