# Generated by Django 3.2.10 on 2023-08-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesrequisitionitem',
            name='size',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
