# Generated by Django 3.2.10 on 2023-07-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesrequisitionbill',
            name='store_receiver',
        ),
    ]
