# Generated by Django 3.2.10 on 2023-08-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesrequisitionitem',
            name='style',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
