# Generated by Django 4.1.7 on 2023-04-12 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0002_accesrequisitionbill_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesrequisitionbill',
            name='name',
        ),
    ]
