# Generated by Django 3.2.10 on 2023-08-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0002_accesrequisitionitem_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesrequisitionitem',
            name='sales_quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
