# Generated by Django 4.2.6 on 2023-11-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0002_accesrequisitionbill_po_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesrequisitionitem',
            old_name='acces_color',
            new_name='color',
        ),
    ]
