# Generated by Django 3.2.10 on 2023-06-20 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('acces_requisition', '0002_alter_accesrequisitionbill_file_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesrequisitionbill',
            name='file_no',
        ),
        migrations.AddField(
            model_name='accesrequisitionbill',
            name='file_no_ar',
            field=models.ForeignKey(default='10000001', on_delete=django.db.models.deletion.CASCADE, related_name='Acces_file_no', to='store.storebill'),
            preserve_default=False,
        ),
    ]
