# Generated by Django 3.2.10 on 2023-07-31 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0002_remove_accesrequisitionbill_store_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesrequisitionbill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
