# Generated by Django 3.2.10 on 2023-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0002_alter_accesrequisitionitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesrequisitionbill',
            name='supply_qty',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accesrequisitionitem',
            name='balance_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accesrequisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
