# Generated by Django 3.2.10 on 2023-08-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0003_accesrequisitionitem_sales_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesrequisitionitem',
            name='sales_quantity',
        ),
        migrations.AddField(
            model_name='accesrequisitionitem',
            name='balance_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
