# Generated by Django 4.1.7 on 2023-04-12 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0003_remove_accesrequisitionbill_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesrequisitionbill',
            old_name='supervisor',
            new_name='name',
        ),
    ]
