# Generated by Django 4.1.7 on 2023-04-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acces_requisition', '0005_rename_sr_designation_accesrequisitionbill_store_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesrequisitionbill',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
