# Generated by Django 3.1.13 on 2022-12-10 06:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store_receiver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRequisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('order_no', models.CharField(blank=True, max_length=32, null=True)),
                ('style_no', models.CharField(blank=True, max_length=32, null=True)),
                ('line_no', models.CharField(blank=True, max_length=32, null=True)),
                ('card_no', models.CharField(blank=True, max_length=32, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('size', models.CharField(choices=[('', 'Select'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=64, null=True)),
                ('required_qty', models.PositiveIntegerField(default=1)),
                ('supply_qty', models.PositiveIntegerField(default=1)),
                ('remarks', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('sr_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_receiver.storereceiver')),
            ],
        ),
    ]
