# Generated by Django 4.1.3 on 2022-11-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_requisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storerequisition',
            name='size',
            field=models.CharField(choices=[('', 'Select'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=64, null=True),
        ),
    ]
