# Generated by Django 3.2.10 on 2023-07-24 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=64, null=True)),
                ('img_profile', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Designation')),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
