# Generated by Django 3.2.10 on 2023-07-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='type',
            field=models.CharField(choices=[('', 'Select'), ('direct_customer', 'Direct Customer'), ('buying_house', 'Buying House')], max_length=64, null=True),
        ),
    ]
