# Generated by Django 3.2.10 on 2023-07-29 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_receiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storereceiver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='storereceiver',
            name='name',
        ),
    ]
