# Generated by Django 4.1.7 on 2023-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereceiver',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
