# Generated by Django 4.1.7 on 2023-05-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='office_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
