# Generated by Django 4.1.7 on 2023-05-09 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiser',
            name='access_area',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='email',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='merchandiser',
            name='joining_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
