# Generated by Django 4.1.7 on 2023-02-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandiser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='merchandiser'),
        ),
    ]
