# Generated by Django 4.1.7 on 2023-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='fabric_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
