# Generated by Django 4.2.6 on 2023-11-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionitem',
            old_name='fab_color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='fabricrequisitionitem',
            old_name='style_no',
            new_name='style',
        ),
    ]
