# Generated by Django 3.2.10 on 2023-07-31 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricrequisitionbill',
            name='store_receiver',
        ),
    ]
