# Generated by Django 4.1.7 on 2023-05-09 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='cutting_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='requard_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
