# Generated by Django 3.2.10 on 2023-06-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionbill',
            old_name='file_no',
            new_name='file_no_store',
        ),
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='wo_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_file_no', to='store.storebill'),
        ),
    ]
