# Generated by Django 4.1.7 on 2023-05-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionbill',
            old_name='fabric_detail',
            new_name='remarks',
        ),
    ]
