# Generated by Django 3.2.10 on 2023-08-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
