# Generated by Django 3.1.13 on 2023-01-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='uom',
            field=models.CharField(choices=[('', 'Select'), ('kg', 'kg'), ('miter', 'miter'), ('yard', 'yard'), ('pcs', 'pcs'), ('pound', 'pound'), ('g', 'g'), ('gg', 'gg'), ('litre', 'litre'), ('dz', 'dz'), ('1000 pcs', '1000 pcs')], max_length=64, null=True),
        ),
    ]
