# Generated by Django 3.2.10 on 2023-08-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remarks', '0001_initial'),
        ('fabric_requi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='remarks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarksname_fabric', to='remarks.remarks'),
        ),
    ]
