# Generated by Django 4.2.6 on 2023-11-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0002_rename_fab_color_fabricrequisitionitem_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionbill',
            old_name='order_no',
            new_name='style_no',
        ),
    ]
