# Generated by Django 3.2.10 on 2023-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0002_auto_20230822_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='balance_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='cutting_qty',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='order_qty',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='requard_qty',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
