# Generated by Django 4.1.7 on 2023-05-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0002_rename_fabric_detail_fabricrequisitionbill_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionbill',
            old_name='po_no',
            new_name='wo_no',
        ),
    ]
