# Generated by Django 3.2.10 on 2023-07-31 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0002_remove_fabricrequisitionbill_store_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
