# Generated by Django 3.2.10 on 2023-08-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0003_auto_20230822_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionitem',
            name='cad_consumption',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
