# Generated by Django 4.1.7 on 2023-05-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0003_rename_po_no_fabricrequisitionbill_wo_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricrequisitionbill',
            name='file_no',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
