# Generated by Django 3.2.10 on 2023-06-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0003_alter_fabricrequisitionbill_wo_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionbill',
            old_name='wo_no',
            new_name='work_order',
        ),
    ]
