# Generated by Django 3.2.10 on 2023-06-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_storebill_supplier'),
        ('fabric_requi', '0004_rename_wo_no_fabricrequisitionbill_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricrequisitionbill',
            name='file_no_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_file_no', to='store.storebill'),
        ),
    ]
