# Generated by Django 4.1.7 on 2023-05-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric_requi', '0004_fabricrequisitionbill_file_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricrequisitionitem',
            old_name='consumption',
            new_name='cad_consumption',
        ),
    ]
